### ISSUE TITLE
No configured Linux kernel sources in <linux source folder>

### ISSUE THREAD

**Issue by xterazer** [veysiadn/IgHEtherCATImplementation#1]
Hi,

When I tride to run the command：

**sudo ./configure --enable-8139too=no --prefix=/opt/etherlab

>>>confiugre:error: Failed to find Linux sources. Usb --with-linux-dir!**

So I use git to pull the kernel from raspberry's repository and use this command:

**sudo ./configure --enable-8139too=no --prefix=/opt/etherlab --with-linux-dir=~/linux

but reply:

>>> No configured Linux kernel sources in ~/linux**

BTW I have use make command in linux folder to make .config file

Thanks

**Comment by veysiadn** [comment]
Hello, for raspberry pi, linux kernel directory must be different, I'm not sure,  I remember that I implemented this on RPI as well, but I don't remember what was the different configuration I did.
I'm guessing that you'll have to properly specify --with-linux-dir to a correct directory.
Please refer to igH documentation : https://gitlab.com/etherlab.org/ethercat/-/jobs/8139472655/artifacts/raw/pdf/ethercat_doc.pdf page 142.

**Comment by xterazer** [comment]
> Hello, for raspberry pi, linux kernel directory must be different, I'm not sure, I remember that I implemented this on RPI as well, but I don't remember what was the different configuration I did. I'm guessing that you'll have to properly specify --with-linux-dir to a correct directory. Please refer to igH documentation : https://gitlab.com/etherlab.org/ethercat/-/jobs/8139472655/artifacts/raw/pdf/ethercat_doc.pdf page 142.

Hi,

You are right! I use sudo apt install linux-headers-rpi to download the header files and use this folder as the parameters of with-linux-dir.

Thank you!
